"use client";
import "./globals.css";
import "./task/homepage.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import store from "../Redux/store";
import firebase from "../../firebaseConfig";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "To-do",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
